import { afterEach, describe, expect, it } from "vitest";
import { Storage } from "@cwb/storage";
import { hashPassword } from "./auth.js";
import { buildServer } from "./server.js";
import type { FastifyInstance } from "fastify";
import { EventEmitter } from "node:events";
import type { RuntimeManager } from "./runtime-manager.js";
let app: FastifyInstance | undefined; let storage: Storage | undefined;
afterEach(async () => { await app?.close(); storage?.close(); });
async function setup() { storage = new Storage(":memory:"); app = await buildServer({ version: 1, bindHost: "127.0.0.1", port: 3210, publicOrigin: "https://bridge.example", passwordHash: await hashPassword("correct horse battery staple"), sessionSecret: "x".repeat(32), trustedProxy: "127.0.0.1" }, storage); }
describe("HTTPS boundary", () => {
  it("returns no information without the trusted HTTPS marker", async () => { await setup(); const reply = await app!.inject({ method: "POST", url: "/api/auth/login", payload: { password: "correct horse battery staple" } }); expect(reply.statusCode).toBe(404); expect(reply.body).toBe(""); });
  it("authenticates through the local HTTPS proxy and protects mutations with CSRF", async () => { await setup(); const login = await app!.inject({ method: "POST", url: "/api/auth/login", headers: { "x-forwarded-proto": "https", origin: "https://bridge.example" }, payload: { password: "correct horse battery staple" } }); expect(login.statusCode).toBe(200); expect(login.headers["set-cookie"]).toContain("Secure"); const csrf = login.json().csrfToken; const cookie = login.cookies[0]!.name + "=" + login.cookies[0]!.value; const logout = await app!.inject({ method: "POST", url: "/api/auth/logout", headers: { "x-forwarded-proto": "https", origin: "https://bridge.example", cookie, "x-csrf-token": csrf } }); expect(logout.statusCode).toBe(204); });
});

class FakeRuntime implements RuntimeManager {
  events=new EventEmitter(); calls:string[]=[];
  async create(){this.calls.push("create");return "codex-1";} async resume(){this.calls.push("resume");} async reconnect(_host:unknown,thread:{remotePort?:number}){this.calls.push(`reconnect:${thread.remotePort}`);}
  async exit(_thread:unknown,host?:{id:string}){this.calls.push(`exit:${host?.id}`);} async send(){this.calls.push("send");return "turn-1";} async interrupt(){this.calls.push("interrupt");} async resolve(){this.calls.push("resolve");}
  async terminalInput(){this.calls.push("input");} async screenshot(){return Buffer.from([137,80,78,71]);} async close(){}
  async terminalSeed(){return "\u001b[31mseed\u001b[0m";}
}
it("wires authenticated thread operations to the runtime",async()=>{storage=new Storage(":memory:");storage.upsertHost({id:"host",name:"A",hostname:"a",port:22,username:"u",hostKeySha256:"key",identityFile:"/key",createdAt:1});const runtime=new FakeRuntime();app=await buildServer({version:1,bindHost:"127.0.0.1",port:3210,publicOrigin:"https://bridge.example",passwordHash:await hashPassword("correct horse battery staple"),sessionSecret:"x".repeat(32),trustedProxy:"127.0.0.1"},storage,{runtime,webRoot:false});const base={"x-forwarded-proto":"https",origin:"https://bridge.example"};const login=await app.inject({method:"POST",url:"/api/auth/login",headers:base,payload:{password:"correct horse battery staple"}}),csrf=login.json().csrfToken,cookie=`${login.cookies[0]!.name}=${login.cookies[0]!.value}`,headers={...base,cookie,"x-csrf-token":csrf};const hosts=await app.inject({method:"GET",url:"/api/hosts",headers:{...base,cookie}});expect(hosts.json()[0]).toMatchObject({id:"host",hostname:"a",port:22,username:"u",hostKeySha256:"key",identityFile:"/key"});const created=await app.inject({method:"POST",url:"/api/threads",headers,payload:{hostId:"host",cwd:"/work"}});expect(created.statusCode).toBe(201);const id=created.json().id;const sent=await app.inject({method:"POST",url:`/api/threads/${id}/messages`,headers,payload:{text:"hi"}});expect(sent.statusCode).toBe(200);expect(sent.json()).toEqual({turnId:"turn-1"});expect((await app.inject({method:"POST",url:`/api/threads/${id}/interrupt`,headers})).statusCode).toBe(204);expect((await app.inject({method:"POST",url:`/api/threads/${id}/terminal/takeover`,headers,payload:{enabled:true}})).statusCode).toBe(204);expect((await app.inject({method:"POST",url:`/api/threads/${id}/terminal/input`,headers,payload:{data:"x"}})).statusCode).toBe(204);expect((await app.inject({method:"GET",url:`/api/threads/${id}/terminal/screenshot`,headers:{...base,cookie}})).statusCode).toBe(200);expect((await app.inject({method:"POST",url:`/api/threads/${id}/exit`,headers})).statusCode).toBe(204);expect(runtime.calls).toEqual(expect.arrayContaining(["create","send","interrupt","input","exit:host"]));});
it("reconnects a persisted active thread on its original remote port",async()=>{storage=new Storage(":memory:");storage.upsertHost({id:"host",name:"A",hostname:"a",port:22,username:"u",hostKeySha256:"key",identityFile:"/key",createdAt:1});storage.createThread({id:"thread",hostId:"host",codexThreadId:"codex",tmuxSession:"cwb-thread",remotePort:45678,workingDirectory:"/work",title:"thread",status:"idle",createdAt:1,updatedAt:1});const runtime=new FakeRuntime();app=await buildServer({version:1,bindHost:"127.0.0.1",port:3210,publicOrigin:"https://bridge.example",passwordHash:await hashPassword("correct horse battery staple"),sessionSecret:"x".repeat(32),trustedProxy:"127.0.0.1"},storage,{runtime,webRoot:false});await new Promise(resolve=>setTimeout(resolve,0));expect(runtime.calls).toContain("reconnect:45678");});
it("expires pending RPC callbacks when the runtime connection generation changes",async()=>{storage=new Storage(":memory:");storage.upsertHost({id:"host",name:"A",hostname:"a",port:22,username:"u",hostKeySha256:"key",identityFile:"/key",createdAt:1});storage.createThread({id:"thread",hostId:"host",codexThreadId:"codex",tmuxSession:"cwb-thread",remotePort:45678,workingDirectory:"/work",title:"thread",status:"waiting",createdAt:1,updatedAt:1});storage.putPending({id:"bridge-request",threadId:"thread",payload:"{}",rpcId:"7",method:"item/tool/requestUserInput",params:"{}",createdAt:1});const runtime=new FakeRuntime();app=await buildServer({version:1,bindHost:"127.0.0.1",port:3210,publicOrigin:"https://bridge.example",passwordHash:await hashPassword("correct horse battery staple"),sessionSecret:"x".repeat(32),trustedProxy:"127.0.0.1"},storage,{runtime,webRoot:false});runtime.events.emit("connectionGenerationChanged",{threadId:"thread"});expect(storage.pending("thread")).toHaveLength(0);const base={"x-forwarded-proto":"https",origin:"https://bridge.example"},login=await app.inject({method:"POST",url:"/api/auth/login",headers:base,payload:{password:"correct horse battery staple"}}),cookie=`${login.cookies[0]!.name}=${login.cookies[0]!.value}`,csrf=login.json().csrfToken;const stale=await app.inject({method:"POST",url:"/api/threads/thread/requests/bridge-request",headers:{...base,cookie,"x-csrf-token":csrf},payload:{answers:{question:{answers:["old"]}}}});expect(stale.statusCode).toBe(409);expect(runtime.calls).not.toContain("resolve");});
